1.0.1.3
	Last working commit using static objects and not pointers.  this version also looks for php's manual in /usr/share/php_manual

Committed on : 2010-07-16 @ 12:48:11 AM

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -420,9 +420,9 @@ SHELL=${CONFIG_SHELL-/bin/sh}
 
 # Identity of this package.
 PACKAGE_NAME=connectED
-PACKAGE_TARNAME=
-PACKAGE_VERSION=1.0.1.2
-PACKAGE_STRING=
+PACKAGE_TARNAME=connectED
+PACKAGE_VERSION=1.0.3
+PACKAGE_STRING="${PACKAGE_NAME} ${PACKAGE_VERSION}"
 PACKAGE_BUGREPORT="http://uberChicGeekChick.Com/?projects=connectED"
 
 ac_unique_file="src"
@@ -1035,6 +1035,9 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
 
+  --enable-php-manual=[/path/to/php/manual]
+                          Where to look for PHP's manual for integrated help.
+
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
@@ -1360,7 +1363,7 @@ rm -rf conftest* confdefs.h
 echo >confdefs.h
 
 # Predefined preprocessor variables.
-
+ 
 cat >>confdefs.h <<_ACEOF
 #define PACKAGE_NAME "$PACKAGE_NAME"
 _ACEOF
@@ -21061,6 +21064,44 @@ echo "${ECHO_T}$LINGUAS" >&6
 	< $srcdir/po/POTFILES.in > po/POTFILES
 
 
+PHP_MANUAL_DIR=""
+echo "$as_me:$LINENO: checking PHP manual directory" >&5
+echo $ECHO_N "checking PHP manual directory... $ECHO_C" >&6
+if test "x$enable_php_manual" != "xNONE"; then
+  PHP_MANUAL_DIR=$enable_php_manual
+fi
+
+if ! test -d "$PHP_MANUAL_DIR" && ! test -L "$PHP_MANUAL_DIR"; then
+	PHP_MANUAL_DIR=""
+	for php_manual_dir in \
+		"$prefix/share/doc/phpmanual" "$prefix/share/doc/phpdoc"	\
+		"/usr/share/doc/phpmanual" "/usr/share/doc/phpdoc"		\
+		"$prefix/share/php-docs-"* "/usr/share/php-docs-"*
+	do
+		printf "\n\tchecking $php_manual_dir";
+		if test -e "$php_manual_dir/html/funcref.html"; then
+			PHP_MANUAL_DIR="$php_manual_dir/html"
+			break
+		elif test -e "$php_manual_dir/funcref.html"; then
+			PHP_MANUAL_DIR="$php_manual_dir"
+			break
+		else
+			unset php_manual_dir
+		fi
+	done
+fi
+
+if test -z "$PHP_MANUAL_DIR"; then
+	printf "\n\t**error:** PHP's manual could not be found.\n\tYou can specify its location with:\n\t\tconfigure --enable-php-manual=[...] option.\n";
+else
+	printf "\n\t$GETTEXT_PACKAGE will use the copy of PHP's manual found in $PHP_MANUAL_DIR\n";
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define PHP_MANUAL_DIR "$PHP_MANUAL_DIR"
+_ACEOF
+
+
 echo "$as_me:$LINENO: checking locale directory" >&5
 echo $ECHO_N "checking locale directory... $ECHO_C" >&6
 if test "x$prefix" = "xNONE"; then
@@ -21077,7 +21118,7 @@ echo "$as_me:$LINENO: result: \"$PACKAGE_LOCALE_DIR\"" >&5
 echo "${ECHO_T}\"$PACKAGE_LOCALE_DIR\"" >&6
 
 
-                                                                                ac_config_files="$ac_config_files Makefile connectED.desktop connectED.spec data/Makefile doc/Makefile pixmaps/Makefile po/Makefile src/Makefile"
+ac_config_files="$ac_config_files Makefile share/Makefile po/Makefile src/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -21654,11 +21695,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  "connectED.desktop" ) CONFIG_FILES="$CONFIG_FILES connectED.desktop" ;;
-  "connectED.spec" ) CONFIG_FILES="$CONFIG_FILES connectED.spec" ;;
-  "data/Makefile" ) CONFIG_FILES="$CONFIG_FILES data/Makefile" ;;
-  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  "pixmaps/Makefile" ) CONFIG_FILES="$CONFIG_FILES pixmaps/Makefile" ;;
+  "share/Makefile" ) CONFIG_FILES="$CONFIG_FILES share/Makefile" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,9 +2,9 @@ dnl
 dnl configure.in for connectED
 dnl
 
-AC_INIT(src, , http://uberChicGeekChick.Com/?projects=connectED)
+AC_INIT("connectED", "1.0.3", "http://uberChicGeekChick.Com/?projects=connectED")
 AM_CONFIG_HEADER(config.h)
-AM_INIT_AUTOMAKE(connectED, 1.0.1.2)
+AM_INIT_AUTOMAKE("connectED", "1.0.3")
 
 AM_MAINTAINER_MODE
 
@@ -17,8 +17,8 @@ dnl  --------------
 dnl | dependencies |-----------------------------------------------------------
 dnl  --------------
 
-PKG_CHECK_MODULES(connectED,[
-	gtk+-2.0 libglade-2.0 libgnomeui-2.0 gnome-vfs-2.0 libgtkhtml-2.0 dnl libgnomeprint-2.2 libgnomeprintui-2.2])
+PKG_CHECK_MODULES("connectED",[
+	gtk+-2.0 libglade-2.0 libgnomeui-2.0 gnome-vfs-2.0 libgtkhtml-2.0] )
 
 AC_SUBST(connectED_CFLAGS)
 AC_SUBST(connectED_LIBS)
@@ -29,14 +29,51 @@ dnl  ------------------
 dnl | language support |-------------------------------------------------------
 dnl  ------------------
 
-GETTEXT_PACKAGE=connectED
+GETTEXT_PACKAGE="connectED"
 AC_SUBST(GETTEXT_PACKAGE)
-AC_DEFINE_UNQUOTED(GETTEXT_PACKAGE,"$GETTEXT_PACKAGE",[The package name, for gettext])
+AC_DEFINE_UNQUOTED(GETTEXT_PACKAGE,"$GETTEXT_PACKAGE",["The package name, for gettext"])
 
 dnl Please keep this in alphabetical order
 ALL_LINGUAS=""
 
 AM_GLIB_GNU_GETTEXT
+
+AC_MSG_CHECKING(PHP manual)
+if test "x$enable_php_manual" != "xNONE"; then
+  PHP_MANUAL_DIR=$enable_php_manual
+fi
+
+if ! test -d "$PHP_MANUAL_DIR" && ! test -L "$PHP_MANUAL_DIR"; then
+	PHP_MANUAL_DIR=""
+	for php_manual_dir in \
+		"$prefix/share/doc/phpmanual" "$prefix/share/doc/phpdoc"	\
+		"/usr/share/doc/phpmanual" "/usr/share/doc/phpdoc"		\
+		"$prefix/share/php-docs-"* "/usr/share/php-docs-"*
+	do
+		printf "\n\tchecking $php_manual_dir";
+		if test -e "$php_manual_dir/html/funcref.html"; then
+			PHP_MANUAL_DIR="$php_manual_dir/html"
+			break
+		elif test -e "$php_manual_dir/funcref.html"; then
+			PHP_MANUAL_DIR="$php_manual_dir"
+			break
+		else
+			unset php_manual_dir
+		fi
+	done
+fi
+
+if test -z "$PHP_MANUAL_DIR"; then
+	printf "\n\t**error:** PHP's manual could not be found.\n\tYou can specify its location with:\n\t\tconfigure --enable-php-manual=[...] option.\n";
+else
+	printf "\n\t$GETTEXT_PACKAGE will use the copy of PHP's manual found in $PHP_MANUAL_DIR\n";
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define PHP_MANUAL_DIR "$PHP_MANUAL_DIR"
+_ACEOF
+
+
 
 dnl AM_GLIB_GNU_GETTEXT sets $DATADIRNAME
 AC_MSG_CHECKING(locale directory)
@@ -46,17 +83,14 @@ else
   PACKAGE_LOCALE_DIR=$prefix/share/locale
 fi
 AC_DEFINE_UNQUOTED(PACKAGE_LOCALE_DIR, "$PACKAGE_LOCALE_DIR",
-	[The directory in which connectED's locale data will be stored])
+	["The directory in which connectED's locale data will be stored"])
 AC_MSG_RESULT("$PACKAGE_LOCALE_DIR")
 
 dnl ---------------------------------------------------------------------------
 
 AC_OUTPUT([
 Makefile
-connectED.desktop
-connectED.spec
-data/Makefile
-doc/Makefile
+share/Makefile
 pixmaps/Makefile
 po/Makefile
 src/Makefile
